version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
        - '3050:80'
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      #here define path of dockerfile
      context: ./server
    volumes:
      # inside docker image dont try to mount , modify this folder, leave it as it is!
      - /app/node_modules
      # host machine ./server will be mounted to /app at docker container (except node_modules)
      - ./server:/app
    environment:
      # just just use service's name
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      #here define path of dockerfile
      context: ./client
    volumes:
      # inside docker image dont try to mount , modify this folder, leave it as it is!
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      #here define path of dockerfile
      context: ./worker
    volumes:
      # inside docker image dont try to mount , modify this folder, leave it as it is!
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379